---
driver:
  name: digitalocean
  ssh_key_ids: 22111299 # vagrant ssh-key

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-18

transport:
  ssh_key: test/fixtures/vagrant

suites:
  - name: default
    run_list:
      - recipe[acme_base::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
